### PR TITLE
Madhav/met 1673 web app enumeration cli

### PR DESCRIPTION
**Pull request by madhavmvats01**
CLI support for web app enumeration CLI. Support for Swagger/OpenAPI 3.0, GraphQL, gRPC enumeration.  

Note: I messed with git attributes for a bit but wasn't able to get it to stop rendering the vendor files. It is probably easiest to review in an IDE. I'm looking for specific feedback on the Fern types and the enumeration functions in the internal folder. Will have a separate PR up to reorganize the CLI as there are now two `fingerprint` commands.

Adds support for the following commands:
**app fingerprint**

Identifies the web application type.
`webscan app fingerprint --type --target`  (type can be swagger, k8s, graphql, grpc)

To test, run:
```
sudo go run main.go vuln --output json --severity INFO --defaultTemplateDirectory ~/method-dev/webscan/configs/configs/templates/develop --customTemplateDirectory ~/method-dev/webscan/configs/configs/templates/custom --tags swagger --target petstore.swagger.io

sudo go run main.go app fingerprint --output json --severity INFO --defaultTemplateDirectory ~/method-dev/webscan/configs/configs/templates/develop --customTemplateDirectory ~/method-dev/webscan/configs/configs/templates/custom --tags graphql --target https://countries.trevorblades.com

```
(Slack me for the gRPC test commandl)

**app enumerate**

Details the routes for an API application.
`webscan app enumerate swagger --target`
`webscan app enumerate grpc --target`
`webscan app enumerate graphql --target`

To test, run:
```
go run main.go app enumerate swagger --target https://dev.method.delivery/ontology/docs/ -o json
go run main.go app enumerate grpc --target grpc.postman-echo.com:443  -o json
go run main.go app enumerate graphql --target https://countries.trevorblades.com/  -o json
```

### CODE REVIEW

**Comment by methodsecuritysj** [comment]
docs are missing for `app` cmd

**Comment by methodsecuritysj** [comment]
With this command: `go run main.go app enumerate swagger --target https://petstore.swagger.io --output json`

There are a lot of logging errors, is that expected? `2024/08/07 13:24:33 ERROR: could not unmarshal event: parse error: expected string near offset 780 of 'cookiePart...'`

**Comment by methodsecuritysj** [comment]
can you be more verbose in the CLI help about what specifically does fingerprinting mean and what specifically does enumeration do

**Comment by methodsecuritysj** [comment]
I think we have been doing camel case in fern fields, I see you have snake case; not sure it matters but better to be consistent

**Comment by methodsecuritysj** [comment]
Sean has standardized the internal functions we call off of cmds to not return an error, I think there are some old ones floating around that haven't conformed to this, but I think you want to change"

`func PerformGraphQLScan(ctx context.Context, target string) (webscan.Report, error) {`

to:

`func PerformGraphQLScan(ctx context.Context, target string) webscan.Report {`

**Comment by methodsecuritysj** [comment]
Change `Report` in your fern def (routes.yml) to something less ambiguous, like RoutesReport

**Comment by methodsecuritysj** [comment]
I think things otherwise look good; I would have put these comments attached to lines but I can't load it in browser

**Comment by madhavmvats01** [comment]
> With this command: `go run main.go app enumerate swagger --target https://petstore.swagger.io --output json`
> 
> There are a lot of logging errors, is that expected? `2024/08/07 13:24:33 ERROR: could not unmarshal event: parse error: expected string near offset 780 of 'cookiePart...'`

this was the chrome dp logging (setup the headless browser to parse the html and look for the docs linked). turned logging to silent

**Review by sean-hacker — APPROVED** [review]

**Pull request merged**
